# Generated by Django 3.1.7 on 2021-04-26 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_auto_20210426_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='organization_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='clients_organization', to='qa.organization', to_field='title'),
        ),
    ]
