# Generated by Django 3.1.7 on 2021-05-04 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0005_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.ForeignKey(default='Открыта', on_delete=django.db.models.deletion.RESTRICT, to='qa.status', to_field='status'),
        ),
    ]
